---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	plan(plan)
	retrieve(retrieve)
	generate(generate)
	verify(verify)
	__end__([<p>__end__</p>]):::last
	__start__ --> plan;
	generate --> verify;
	plan --> retrieve;
	retrieve -.-> generate;
	retrieve -. &nbsp;replan&nbsp; .-> plan;
	verify -. &nbsp;end&nbsp; .-> __end__;
	verify -. &nbsp;regenerate&nbsp; .-> generate;
	verify -. &nbsp;replan&nbsp; .-> plan;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc

